### ISSUE TITLE
`async-icq` repo should move to `cosmos/ibc-apps`

### ISSUE THREAD

**Issue by jonathanpberger** [strangelove-ventures/async-icq#29]

**Comment by jtieri** [comment]
Migration has begun and the first PR can be found [here](https://github.com/cosmos/ibc-apps/pull/6)!

**Comment by jonathanpberger** [comment]
IBC-Apps needs to have the rest of supported branches moved over; when that's done, this ticket will be done.

**Comment by jtieri** [comment]
I just finished migrating all the supported branches and tags to the new [ibc-apps repo](https://github.com/cosmos/ibc-apps). 

Tags can be found [here](https://github.com/cosmos/ibc-apps/tags)
Branches can be found here for
- [v4](https://github.com/cosmos/ibc-apps/tree/async-icq/v4.0.x)
- [v5](https://github.com/cosmos/ibc-apps/tree/async-icq/v5.0.x)
- [v6](https://github.com/cosmos/ibc-apps/tree/async-icq/v6.0.x)
- [v7](https://github.com/cosmos/ibc-apps/pull/13)

`v7` is still just a PR but once it is merged that will be the version maintained in the main branch.

Closing this issue out now.
