### ISSUE TITLE
Research Quasar <> Osmosis ICQ use case for account balances

### ISSUE THREAD

**Issue by kcdenman** [strangelove-ventures/async-icq#33]

**Comment by jonathanpberger** [comment]
@jtieri how do we know when we're done w/ this research?

**Comment by jonathanpberger** [comment]
@jonathanpberger let's pair on this! Put some time on my cal.

**Comment by jonathanpberger** [comment]
...and by ☝ I mean cc @jtieri

**Comment by jtieri** [comment]
I have prepared a few questions for the Quasar team which I will share in Slack.

1. Right now it looks like Quasar is only using ICQ to query account balances on Osmosis. Can you describe your use case, i.e. in what way does this data get used inside of Quasars application and why is it important?
2. Why is the async-icq implementation more desirable for your product vs. the implementation done by [Quicksilver](https://github.com/ingenuity-build/quicksilver/tree/main/x/interchainquery)
3. In what other ways can you envision Quasar using async-icq in the future?

I will post answers here when I have them!

**Comment by jtieri** [comment]
AK from the Quasar team got back to me with a few responses to these questions.

1. Please check here - 
Query Prep - https://github.com/quasar-finance/quasar/blob/main/smart-contracts/contracts/lp-strategy/src/icq.rs#L75 Handle Resp - >  https://github.com/quasar-finance/quasar/blob/main/smart-contracts/contracts/lp-strategy/src/ibc.rs#L319
List of query we are making is here - https://github.com/quasar-finance/quasar/blob/main/smart-contracts/contracts/lp-strategy/src/icq.rs#L135
/cosmos.bank.v1beta1.Query/Balance
/osmosis.gamm.v1beta1.Query/CalcJoinPoolShares
/osmosis.gamm.v1beta1.Query/CalcExitPoolCoinsFromShares
/osmosis.gamm.v2.Query/SpotPrice
/osmosis.lockup.Query/LockedByID

Response values are used to do various calculations and adjustment in the strategy for bond, unbond actions.

2. Looking into this

3. In future we could connect with other zones/dex like upcoming dydx , liquid staking zones, or any other type of defi investment zone where we see enough opportunity. It could also be used to determine when other zones are going for upgrades accordingly we could pause activity on those zones.

**Comment by boojamya** [comment]
This should be the minimum viable need for use case research.
