### ISSUE TITLE
If a query panics an error acknowledgement is not sent.

### ISSUE THREAD

**Issue by VitalyV1337** [strangelove-ventures/async-icq#64]
Example:

Let's say I want to query `GetCmdEstimateSwapExactAmountIn` from Osmosis, if you're querying a stableswap pool and enter more tokens than there are in a pool it will panic [Here](https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/pool-models/stableswap/amm.go#L118) this will not cause the query to return an error thus `async-icq` will not return an `ack-err`.

**Comment by akc2267** [comment]
Hey please follow up with Osmosis team in the Cosmos/ibc-apps repo
